version: "3.7"

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ctfbot
      POSTGRES_PASSWORD: ctfbot
      POSTGRES_DB: ctfbot
    volumes:
      - db-volume:/var/lib/postgresql/data

volumes:
  db-volume:
