version: "3.7"

services:
  ctfbot:
    build:
      context: .
    ports:
      - 0.0.0.0:8443:8443
    depends_on:
      - postgres
  postgres:
    image: postgres:14.0
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: ctfbot
      POSTGRES_PASSWORD: ctfbot
      POSTGRES_DB: ctfbot
    volumes:
      - .data/postgres:/var/lib/postgresql/data
